/*
 * GENERATED by scratchpad/library/build.mjs — do not edit by hand.
 * One entry per scenario video in public/videos/<slug>.mp4 (+ .jpg poster).
 */

export type VideoSlug =
  | 'setup'
  | 'reservation'
  | 'cooling-off-cancellation'
  | 'exchange'
  | 'choices'
  | 'major-change'
  | 'delay'
  | 'notice-inspection'
  | 'completion'
  | 'snag'
  | 'complaint'
  | 'emergency'
  | 'emails'
  | 'ombudsman'

export const VIDEOS: Record<VideoSlug, { title: string; code: string; duration: number }> = {
  'setup': { title: "First setup", code: "Settings", duration: 40 },
  'reservation': { title: "Reservation day", code: "Code 2.2 · 2.3", duration: 60 },
  'cooling-off-cancellation': { title: "If the sale falls through", code: "Code 2.4 · 2.13", duration: 43 },
  'exchange': { title: "Exchange of contracts", code: "Code 2.2 · 2.6 · 2.7", duration: 50 },
  'choices': { title: "Choices, extras and site visits", code: "Code 2.2 · 2.6", duration: 66 },
  'major-change': { title: "A major change", code: "Code 2.9", duration: 64 },
  'delay': { title: "A delay", code: "Code 2.7 · 2.8", duration: 59 },
  'notice-inspection': { title: "Notice to complete and inspection", code: "Code 2.8", duration: 65 },
  'completion': { title: "Completion and handover", code: "Code 2.11 · 2.12 · 3.1", duration: 56 },
  'snag': { title: "A snag or defect", code: "Code 3.3", duration: 77 },
  'complaint': { title: "A formal complaint", code: "Code 3.4 · 3.5", duration: 81 },
  'emergency': { title: "An emergency", code: "Code 3.1 · 3.3 · glossary", duration: 66 },
  'emails': { title: "Emails in the record", code: "The evidence trail", duration: 54 },
  'ombudsman': { title: "Formal complaints to the Ombudsman", code: "Code 3.5", duration: 50 },
}
