/*
 * Write src/lib/videoLibrary.ts from manifest.json, and refresh the tour's
 * length and "Watch in the tour" timestamps in GuideTab.tsx.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { ORDER } from './scripts.mjs'
import { HERE } from './tts.mjs'

const ROOT = resolve(HERE, '..', '..')
const manifest = JSON.parse(readFileSync(join(HERE, 'manifest.json'), 'utf8'))

const missing = ORDER.filter((s) => !manifest.videos[s])
if (missing.length) throw new Error(`Not recorded yet: ${missing.join(', ')}`)

const lines = [
  '/*',
  ' * GENERATED by tools/media/library.mjs from tools/media/manifest.json — do not edit by hand.',
  ' * One entry per scenario video in public/videos/<slug>.mp4 (+ .jpg poster).',
  ' */',
  '',
  'export type VideoSlug =',
  ...ORDER.map((s) => `  | '${s}'`),
  '',
  'export const VIDEOS: Record<VideoSlug, { title: string; code: string; duration: number }> = {',
  ...ORDER.map((s) => {
    const v = manifest.videos[s]
    return `  '${s}': { title: ${JSON.stringify(v.title)}, code: ${JSON.stringify(v.code)}, duration: ${v.duration} },`
  }),
  '}',
  '',
]
writeFileSync(join(ROOT, 'src', 'lib', 'videoLibrary.ts'), lines.join('\n'))
console.log('src/lib/videoLibrary.ts written')

if (manifest.tour?.duration) {
  const guidePath = join(ROOT, 'src', 'components', 'GuideTab.tsx')
  let guide = readFileSync(guidePath, 'utf8')
  guide = guide.replace(/const TOUR_DURATION = \d+/, `const TOUR_DURATION = ${manifest.tour.duration}`)
  for (const [title, at] of Object.entries(manifest.tour.watchAt || {})) {
    const re = new RegExp(`(title: '${title.replace(/'/g, "\\\\'")}',\\n\\s*watchAt: )\\d+`)
    if (!re.test(guide)) throw new Error(`GuideTab: no watchAt for section "${title}"`)
    guide = guide.replace(re, `$1${at}`)
  }
  writeFileSync(guidePath, guide)
  console.log(`GuideTab.tsx: tour ${manifest.tour.duration}s, watchAt ${JSON.stringify(manifest.tour.watchAt)}`)
}
