/*
 * What each video shows, beat by beat. Every scenario calls h.beat() exactly
 * once per line in scripts.mjs; the harness holds each beat for its narration.
 * Each starts from the demo development, which has one plot at every stage:
 *   Plot 9  reserved, cooling-off live      Plot 5  exchanged, major change live
 *   Plot 1  completed, nothing open         Plot 2  completed, snag due in 3 days
 *   Plot 7  completed, complaint + emergency, emails on record
 */
import {
  APP,
  closeSheet,
  copyCustomerLink,
  customerReport,
  freshApp,
  navigate,
  openDevelopment,
  openPlot,
  patchState,
  reportLinkFrom,
  scrollSheetTo,
  scrollTo,
  type,
} from './harness.mjs'

const CUSTOMER_CARD = { big: 'Your customer', logo: false }

function isoDaysFromToday(n) {
  const d = new Date()
  d.setDate(d.getDate() + n)
  const y = d.getFullYear()
  const m = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}

async function titleCard(h, meta) {
  await h.card({ kicker: meta.code.toUpperCase(), title: meta.title, sub: 'What you do — and what your customer sees' })
}

/** "Now, your customer": the interstitial, then the customer's page from a link copied a moment ago. */
async function toCustomer(h, page, link) {
  await h.card(CUSTOMER_CARD)
  await h.beat()
  await h.waitUntil(1.6)
  await navigate(page, link)
}

async function openLog(page, kind) {
  await page.getByRole('button', { name: 'Log a choice, change, delay, visit or email' }).click()
  await page.waitForTimeout(350)
  if (kind) {
    await page.locator('.sheet .type-opt', { hasText: kind }).first().click()
    await page.waitForTimeout(250)
  }
}

async function editDetails(page) {
  await page.getByRole('button', { name: 'Edit details & dates' }).click()
  await page.waitForTimeout(350)
}

async function fillDate(page, label, iso) {
  const field = page.locator('.sheet .field', { hasText: label }).first()
  await field.locator('input[type=date]').fill(iso)
  await page.waitForTimeout(200)
}

async function tick(page, label) {
  await page.getByRole('button', { name: `Mark "${label}" done` }).click()
  await page.waitForTimeout(350)
}

export const SCENARIO_RUNNERS = {
  async setup(h, page, meta) {
    await freshApp(page, { unlocked: false, demo: false })
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await h.waitUntil(1.8)
    await type(page, page.getByPlaceholder('Access code'), 'NHQB-HOME-2026', 110)
    await page.waitForTimeout(1200)
    await page.getByRole('button', { name: 'Continue' }).click()
    await page.waitForTimeout(3200)
    await page.getByRole('button', { name: 'Got it' }).click()
    await h.beat()
    await page.getByRole('button', { name: 'Settings' }).click()
    await page.waitForTimeout(400)
    await type(page, page.getByPlaceholder('e.g. Meadow Homes Ltd'), 'Meadow Homes Ltd', 45)
    await type(page, page.getByPlaceholder('e.g. you@yourcompany.co.uk'), 'customercare@meadowhomes.co.uk', 40)
    await h.beat()
    await scrollSheetTo(page, page.getByRole('button', { name: 'Download backup' }), 160)
    await page.waitForTimeout(900)
    await page.getByRole('button', { name: 'Download backup' }).click()
    await h.beat()
    await closeSheet(page)
    await h.beat()
  },

  async reservation(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await page.getByRole('button', { name: '+ Plot' }).click()
    await page.waitForTimeout(350)
    await type(page, page.getByPlaceholder('e.g. Plot 3, Meadow View'), 'Plot 3, Meadow View')
    await type(page, page.getByPlaceholder('e.g. Mr & Mrs Patel'), 'Mr & Mrs Patel')
    await type(page, page.getByPlaceholder('e.g. customer@email.com'), 'patel.family@example.com', 22)
    await page.waitForTimeout(500)
    await page.getByRole('button', { name: 'Create plot' }).click()
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: 'Journey' }), 90)
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: /Document checklist/ }), 60)
    await page.waitForTimeout(800)
    await tick(page, 'Reservation Agreement signed, copy given to customer')
    await tick(page, 'Affordability Schedule provided')
    await h.beat()
    await scrollTo(page, page.getByRole('button', { name: 'Share with customer' }), 200)
    await page.getByRole('button', { name: 'Share with customer' }).click()
    await page.waitForTimeout(600)
    await page.getByRole('button', { name: /Copy link/ }).click()
    await page.waitForTimeout(250)
    const link = await page.evaluate(() => navigator.clipboard.readText())
    await h.settle()
    await closeSheet(page)
    await toCustomer(h, page, link)
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: 'Where am I in the process?' }), 70)
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: 'How am I protected?' }), 70)
  },

  async 'cooling-off-cancellation'(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 9')
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await page.waitForTimeout(600)
    await editDetails(page)
    await page.waitForTimeout(700)
    await scrollSheetTo(page, page.getByRole('heading', { name: 'If the customer pulls out' }), 90)
    await h.beat()
    await page.waitForTimeout(600)
    await page.getByRole('button', { name: 'Reservation cancelled' }).click()
    await page.waitForTimeout(500)
    await scrollTo(page, page.getByRole('heading', { name: 'Journey' }), 90)
    await h.beat()
    await h.beat()
    await page.waitForTimeout(900)
    await page.getByRole('button', { name: 'Mark refund paid' }).click()
    await page.waitForTimeout(1500)
    await page.getByRole('button', { name: 'Back' }).click()
    await page.waitForTimeout(500)
    await page.getByRole('button', { name: /Show archived plots/ }).click()
    await page.waitForTimeout(200)
    await scrollTo(page, page.getByRole('button', { name: /Hide archived plots/ }), 60)
  },

  async exchange(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 9')
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await scrollTo(page, page.getByText('Pre-contract & exchange'), 60)
    await page.waitForTimeout(900)
    await tick(page, 'Pre-contract information sent to customer’s legal adviser')
    await tick(page, 'Contract of sale terms confirmed compliant')
    await h.beat()
    await scrollTo(page, page.getByRole('button', { name: 'Edit details & dates' }), 200)
    await editDetails(page)
    await scrollSheetTo(page, page.locator('.sheet .field', { hasText: 'Exchange of contracts' }), 120)
    await fillDate(page, 'Exchange of contracts', isoDaysFromToday(0))
    await page.waitForTimeout(500)
    await page.getByRole('button', { name: 'Save' }).click()
    await page.waitForTimeout(400)
    await scrollTo(page, page.getByRole('heading', { name: 'Journey' }), 90)
    await h.settle()
    const link = await copyCustomerLink(page)
    await toCustomer(h, page, link)
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: 'Where am I in the process?' }), 90)
  },

  async choices(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 9')
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await openLog(page)
    await type(page, page.locator('.sheet textarea'), 'Kitchen units confirmed: Shaker, sage green', 30)
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Log choice' }).click()
    await h.beat()
    await openLog(page, 'Extra')
    await type(page, page.locator('.sheet textarea'), 'Quartz worktop upgrade ordered — £1,850 paid', 30)
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Log extra' }).click()
    await h.beat()
    await openLog(page, 'Site visit')
    await type(page, page.locator('.sheet textarea'), 'Electrician 9am — no access, card left', 30)
    await page.waitForTimeout(600)
    await page.getByRole('button', { name: 'Log site visit' }).click()
    await page.waitForTimeout(300)
    await scrollTo(page, page.getByRole('heading', { name: /Spec & changes/ }), 60)
    await h.settle()
    const link = await copyCustomerLink(page)
    await toCustomer(h, page, link)
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: /Choices & changes/ }), 60)
    await h.beat()
    await scrollTo(page, page.getByRole('button', { name: /Report a problem/ }), 200)
    await page.waitForTimeout(400)
    await customerReport(page, { category: 'A missed appointment', text: 'The electrician did not come on Tuesday as arranged. I waited in all morning.' })
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: /Your reports/ }), 60)
  },

  async 'major-change'(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 9')
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await openLog(page, 'Major change')
    await page.waitForTimeout(600)
    await type(page, page.locator('.sheet textarea'), 'Kitchen/diner window moved to the side elevation after the drainage redesign', 26)
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Log major change' }).click()
    await page.waitForTimeout(700)
    await h.beat()
    await scrollSheetTo(page, page.getByRole('button', { name: 'Record the notice as received' }), 160)
    await page.waitForTimeout(1200)
    await page.getByRole('button', { name: 'Record the notice as received' }).click()
    await page.waitForTimeout(1600)
    await closeSheet(page)
    await scrollTo(page, page.getByRole('heading', { name: 'Journey' }), 90)
    await h.settle()
    const link = await copyCustomerLink(page)
    await toCustomer(h, page, link)
    await h.beat()
    await scrollTo(page, page.getByText(/written details of a major change/), 120)
    await h.beat()
    await navigate(page, APP)
    await openDevelopment(page)
    await openPlot(page, 'Plot 9')
    await scrollTo(page, page.getByRole('heading', { name: /Spec & changes/ }), 60)
    await page.waitForTimeout(700)
    await page.getByRole('button', { name: 'Record outcome' }).first().click()
  },

  async delay(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 5')
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await openLog(page, 'Delay')
    await type(page, page.locator('.sheet textarea'), 'Completion moved back three weeks — roof trusses delayed by the supplier', 28)
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Log delay' }).click()
    await page.waitForTimeout(300)
    await scrollTo(page, page.getByRole('heading', { name: /Spec & changes/ }), 60)
    await h.beat()
    await page.getByRole('button', { name: 'Draft update' }).first().click()
    await h.beat()
    await closeSheet(page)
    await scrollTo(page, page.getByRole('button', { name: 'Edit details & dates' }), 200)
    await editDetails(page)
    await scrollSheetTo(page, page.locator('.sheet .field', { hasText: 'Expected completion' }), 120)
    await fillDate(page, 'Expected completion', isoDaysFromToday(91))
    await page.waitForTimeout(500)
    await page.getByRole('button', { name: 'Save' }).click()
    await page.waitForTimeout(300)
    await scrollTo(page, page.getByRole('heading', { name: 'Journey' }), 90)
    await h.settle()
    const link = await copyCustomerLink(page)
    await toCustomer(h, page, link)
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: 'Where am I in the process?' }), 70)
    await h.waitUntil(5)
    await scrollTo(page, page.getByRole('heading', { name: /Choices & changes/ }), 60)
  },

  async 'notice-inspection'(h, page, meta) {
    await freshApp(page)
    // The demo plot's major-change window is still open, and Code 2.9 says
    // notice to complete cannot be served inside it — so for this story the
    // change was notified three weeks ago and accepted: its window has closed.
    await patchState(page, (state, today) => {
      const p = state.plots.find((x) => x.address === 'Plot 5, Meadow View')
      const c = p.changes.find((x) => x.kind === 'major_change')
      const d = (n) => {
        const t = new Date(today)
        t.setDate(t.getDate() + n)
        return t.toISOString().slice(0, 10)
      }
      c.date = d(-24)
      c.noticeSentOn = d(-22)
      c.outcome = 'accepted'
      c.outcomeDate = d(-10)
    })
    await openDevelopment(page)
    await openPlot(page, 'Plot 5')
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await editDetails(page)
    await scrollSheetTo(page, page.locator('.sheet .field', { hasText: 'Notice to complete served' }), 120)
    await fillDate(page, 'Notice to complete served', isoDaysFromToday(0))
    await fillDate(page, 'Expected completion', isoDaysFromToday(21))
    await page.waitForTimeout(500)
    await page.getByRole('button', { name: 'Save' }).click()
    await page.waitForTimeout(300)
    await scrollTo(page, page.getByRole('heading', { name: 'Journey' }), 90)
    await h.beat()
    await scrollTo(page, page.getByText('Offer the pre-completion inspection'), 140)
    await h.beat()
    await scrollTo(page, page.getByText('Completion & handover'), 60)
    await page.waitForTimeout(1200)
    await tick(page, 'Pre-completion inspection offered / carried out')
    await h.beat()
    await scrollTo(page, page.getByRole('button', { name: /^Snag/ }), 160)
    await page.getByRole('button', { name: /^Snag/ }).click()
    await page.waitForTimeout(400)
    await type(page, page.locator('.sheet textarea'), 'Scratch on the hall radiator; grout missing behind the bath', 28)
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Log snag' }).click()
    await h.settle()
    const link = await copyCustomerLink(page)
    await toCustomer(h, page, link)
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: 'Where am I in the process?' }), 70)
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: /On your developer's record/ }), 70)
  },

  async completion(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 5')
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await editDetails(page)
    await scrollSheetTo(page, page.locator('.sheet .field', { hasText: 'Notice to complete served' }), 120)
    await fillDate(page, 'Notice to complete served', isoDaysFromToday(-14))
    await fillDate(page, 'Legal completion', isoDaysFromToday(0))
    await page.waitForTimeout(500)
    await page.getByRole('button', { name: 'Save' }).click()
    await page.waitForTimeout(300)
    await scrollTo(page, page.getByRole('heading', { name: 'Journey' }), 90)
    await h.beat()
    await scrollTo(page, page.getByText('Completion & handover'), 60)
    for (const label of [
      'Pre-completion inspection offered / carried out',
      'New home warranty in place — evidence held',
      'Schedule of Incomplete Work (Home) issued',
      'Home demonstration appointment provided',
      'Warranty documentation provided',
      'Complaints procedure copy given to customer',
    ]) {
      await tick(page, label)
      await page.waitForTimeout(250)
    }
    await scrollTo(page, page.getByRole('button', { name: 'Mark "Health & safety file provided" done' }), 200)
    await tick(page, 'Health & safety file provided')
    await tick(page, 'After-sales service written statement given')
    await h.waitUntil(h.dur[h.k] - 1.6)
    const link = await copyCustomerLink(page)
    await h.card(CUSTOMER_CARD)
    await page.waitForTimeout(1400)
    await navigate(page, link)
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: /Documents you have received/ }), 60)
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: 'Where am I in the process?' }), 70)
  },

  async snag(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 1')
    await titleCard(h, meta)
    await h.beat()
    await h.waitUntil(7)
    await h.uncard()
    await h.settle()
    const link = await copyCustomerLink(page)
    await toCustomer(h, page, link)
    await page.waitForTimeout(500)
    const email = await customerReport(page, { category: 'A problem with the home', text: 'Bathroom door catches the frame at the top and will not close.' })
    await h.beat()
    await navigate(page, reportLinkFrom(email))
    await page.waitForTimeout(2500)
    await page.getByRole('button', { name: 'Log snag' }).click()
    await h.beat()
    await scrollTo(page, page.getByRole('heading', { name: /Issues & deadlines/ }), 60)
    await h.settle()
    const link2 = await copyCustomerLink(page)
    await h.beat()
    await navigate(page, link2)
    await scrollTo(page, page.getByRole('heading', { name: /On your developer's record/ }), 70)
  },

  async complaint(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 1')
    await titleCard(h, meta)
    await h.beat()
    await h.uncard()
    await h.settle()
    const link = await copyCustomerLink(page)
    await toCustomer(h, page, link)
    await page.waitForTimeout(500)
    const email = await customerReport(page, {
      category: 'Money or a refund',
      text: 'I paid £1,850 for the quartz worktop upgrade but the standard worktop was fitted. I would like the difference refunded.',
    })
    await h.beat()
    await navigate(page, reportLinkFrom(email))
    await page.waitForTimeout(2500)
    await page.getByRole('button', { name: 'Log complaint' }).click()
    await page.waitForTimeout(400)
    await scrollTo(page, page.getByRole('heading', { name: /Issues & deadlines/ }), 60)
    await h.beat()
    await scrollTo(page, page.getByText('Complaint Assessment and Response letter').first(), 200)
    await h.beat()
    await page.getByRole('button', { name: 'Draft', exact: true }).first().click()
    await h.beat()
    await closeSheet(page)
    const link2 = await copyCustomerLink(page)
    await navigate(page, link2)
    await scrollTo(page, page.getByRole('heading', { name: /On your developer's record/ }), 70)
  },

  async emergency(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 1')
    await titleCard(h, meta)
    await h.beat()
    await h.waitUntil(6.5)
    await h.uncard()
    await h.settle()
    const link = await copyCustomerLink(page)
    await toCustomer(h, page, link)
    await page.waitForTimeout(400)
    await scrollTo(page, page.getByRole('button', { name: /Report a problem/ }), 200)
    await page.getByRole('button', { name: /Report a problem/ }).click()
    await h.beat()
    await page.waitForTimeout(700)
    await page.getByText('Emergency — immediate threat', { exact: true }).click()
    await page.waitForTimeout(600)
    await type(page, page.locator('.sheet textarea'), 'Water pouring through the kitchen ceiling light. I have turned the stopcock off.', 28)
    await page.waitForTimeout(500)
    await page.getByRole('button', { name: /Copy to send another way/ }).click()
    await page.waitForTimeout(300)
    const email = await page.evaluate(() => navigator.clipboard.readText())
    await h.beat()
    await navigate(page, reportLinkFrom(email))
    await page.waitForTimeout(2500)
    await page.getByRole('button', { name: 'Log emergency' }).click()
    await page.waitForTimeout(400)
    await scrollTo(page, page.getByRole('heading', { name: /Issues & deadlines/ }), 60)
    await h.beat()
    await page.waitForTimeout(1500)
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  },

  async emails(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 7')
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await openLog(page, 'Email')
    await page.waitForTimeout(500)
    await page.getByRole('button', { name: 'To the customer', exact: true }).click()
    await type(page, page.getByPlaceholder('e.g. Re: kitchen visit Tuesday'), 'Re: damp patch — specialist visit Thursday', 30)
    await page.locator('.sheet textarea').fill('Hi Ali,\n\nThe damp specialist is booked for Thursday at 9am. They will also check the external pointing while on site.\n\nBest wishes,\nSam')
    await h.beat()
    await scrollSheetTo(page, page.locator('.sheet .field', { hasText: 'Date the email was sent' }), 100)
    await fillDate(page, 'Date the email was sent', isoDaysFromToday(-2))
    await h.beat()
    await scrollSheetTo(page, page.getByRole('button', { name: 'Log email' }), 400)
    await page.getByRole('button', { name: 'Log email' }).click()
    await page.waitForTimeout(400)
    await scrollTo(page, page.getByRole('heading', { name: /Correspondence/ }), 60)
    await h.waitUntil(5)
    await scrollTo(page, page.getByRole('heading', { name: /Records & export/ }), 60)
    await h.beat()
  },

  async ombudsman(h, page, meta) {
    await freshApp(page)
    await openDevelopment(page)
    await openPlot(page, 'Plot 7')
    await titleCard(h, meta)
    await h.beat()
    await h.beat()
    await h.uncard()
    await scrollTo(page, page.getByText('Eight-Week Letter').first(), 200)
    await h.settle()
    const link = await copyCustomerLink(page)
    await h.beat()
    await navigate(page, link)
    await scrollTo(page, page.getByRole('heading', { name: /On your developer's record/ }), 70)
    await h.waitUntil(4)
    await scrollTo(page, page.getByText('The New Homes Ombudsman Service (NHOS)'), 120)
    await h.beat()
    await navigate(page, APP)
    await openDevelopment(page)
    await openPlot(page, 'Plot 7')
    await scrollTo(page, page.getByRole('heading', { name: /Records & export/ }), 60)
    await h.beat()
  },
}

/** The tour — the whole app in one pass. */
export async function tour(h, page) {
  await freshApp(page)
  await h.card({ title: 'New Home Tracker', sub: 'Tracks every new home you sell, keeps customers updated, and helps you keep to the Code.' })
  await h.beat()
  await h.beat()
  await h.uncard()
  await h.beat()
  await openDevelopment(page)
  await h.beat()
  await openPlot(page, 'Plot 5')
  await h.beat()
  await scrollTo(page, page.getByRole('heading', { name: 'Journey' }), 90)
  await h.beat()
  await scrollTo(page, page.getByRole('heading', { name: /Spec & changes/ }), 60)
  await h.beat()
  await scrollTo(page, page.getByRole('button', { name: 'Log a choice, change, delay, visit or email' }), 300)
  await page.getByRole('button', { name: 'Log a choice, change, delay, visit or email' }).click()
  await h.waitUntil(5)
  await closeSheet(page)
  await h.beat()
  await page.getByRole('button', { name: 'Back' }).click()
  await page.waitForTimeout(300)
  await openPlot(page, 'Plot 7')
  await scrollTo(page, page.getByText('Persistent damp patch'), 140)
  await h.beat()
  await page.getByRole('button', { name: 'Draft', exact: true }).first().click()
  await h.beat()
  await closeSheet(page)
  await scrollTo(page, page.getByRole('heading', { name: /Correspondence/ }), 60)
  await h.beat()
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.waitForTimeout(300)
  await page.getByRole('button', { name: 'Share with customer' }).click()
  await page.waitForTimeout(600)
  await page.getByRole('button', { name: /Copy link/ }).click()
  await page.waitForTimeout(250)
  const link = await page.evaluate(() => navigator.clipboard.readText())
  await h.settle()
  await closeSheet(page)
  await h.beat()
  await navigate(page, link)
  await h.waitUntil(4)
  await scrollTo(page, page.getByRole('heading', { name: 'How am I protected?' }), 70)
  await h.beat()
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await scrollTo(page, page.getByRole('button', { name: /Report a problem/ }), 200)
  await page.getByRole('button', { name: /Report a problem/ }).click()
  await page.waitForTimeout(1800)
  await page.getByText('A problem with the home', { exact: true }).click()
  await page.waitForTimeout(600)
  await type(page, page.locator('.sheet textarea'), 'The bedroom window will not lock.', 40)
  await h.beat()
  await navigate(page, APP)
  await page.getByRole('button', { name: 'The Code' }).click()
  await page.waitForTimeout(500)
  await type(page, page.locator('.content textarea'), 'how long to fix a snag', 45)
  await h.beat()
  await h.card({ big: 'Free · Always accessible · Continued Code compliance', url: 'plotclock.co.uk' })
}
